SELECT CONCAT(CASE
    WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN 1
    WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN 2
    WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN 3
    ELSE 4 END, 'Q'
) QUARTER, COUNT(ID) ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER;
