WITH A AS(
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
)

SELECT SCORE, H.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES H, A
WHERE H.EMP_NO = A.EMP_NO;
