WITH RECURSIVE GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT e.ID, e.PARENT_ID, g.GEN+1 AS GEN
    FROM ECOLI_DATA e
    INNER JOIN GENERATION g ON e.PARENT_ID = g.ID
)

SELECT COUNT(*) AS COUNT, g.GENERATION AS GENERATION
FROM GENERATION g
LEFT JOIN ECOLI_DATA child ON g.ID = child.PARENT_ID
WHERE child.ID IS NULL
GROUP BY g.GENERATION
ORDER BY g.GENERATION;
