WITH P AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
F AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
C AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
)

SELECT CASE 
    WHEN P.CODE & SKILL_CODE AND F.CODE & SKILL_CODE THEN 'A'
    WHEN C.CODE & SKILL_CODE THEN 'B'
    WHEN F.CODE & SKILL_CODE THEN 'C'  
END GRADE, ID, EMAIL
FROM DEVELOPERS, P, F, C
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;
