WITH RECURSIVE GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT e.ID, e.PARENT_ID, g.GEN+1 AS GEN
    FROM ECOLI_DATA e
    INNER JOIN GENERATION g ON e.PARENT_ID = g.ID
)

SELECT ID
FROM GENERATION
WHERE GEN = 3
ORDER BY ID;
