SELECT E.EMP_NO, EMP_NAME,
CASE
    WHEN AVG_SCORE >= 96 THEN 'S'
    WHEN AVG_SCORE >= 90 THEN 'A'
    WHEN AVG_SCORE >= 80 THEN 'B'
    ELSE 'C'
END
GRADE,
CASE 
    WHEN AVG_SCORE >= 96 THEN (SAL/100*20)
    WHEN AVG_SCORE >= 90 THEN (SAL/100*15)
    WHEN AVG_SCORE >= 80 THEN (SAL/100*10)  
    ELSE 0
END
BONUS
FROM HR_EMPLOYEES E 
JOIN (SELECT EMP_NO, AVG(SCORE) AVG_SCORE FROM HR_GRADE GROUP BY EMP_NO) SB
ON E.EMP_NO = SB.EMP_NO
ORDER BY E.EMP_NO;
