SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '세단' AND MONTH(H.start_date) = 10
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;
