WITH A AS(
    SELECT CAR_ID, '대여중' AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)

SELECT DISTINCT(C.CAR_ID) CAR_ID, IFNULL(A.AVAILABILITY, '대여 가능') AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
LEFT OUTER JOIN A ON C.CAR_ID = A.CAR_ID
ORDER BY CAR_ID DESC;
