WITH A AS(
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
)

SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER U JOIN A
ON U.USER_ID = A.WRITER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;
