SELECT CONCAT("/home/grep/src/",F.BOARD_ID,"/",FILE_ID,FILE_NAME,FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE F
JOIN USED_GOODS_BOARD B ON F.board_id = B.board_id
WHERE B.views = (SELECT MAX(views) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC;
