SELECT 
    ANIMAL_ID,
    NAME, 
    IF(SEX_UPON_INTAKE REGEXP '^Neutered|^Spayed', 'O', 'X') 중성화
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID;

/* ORACLE
SELECT 
    ANIMAL_ID, 
    NAME, 
    CASE WHEN REGEXP_LIKE(SEX_UPON_INTAKE,'^Neutered|^Spayed') THEN 'O' ELSE 'X' END 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;
*/
