SELECT 
    YEAR(O.SALES_DATE) YEAR, 
    MONTH(O.SALES_DATE) MONTH, 
    GENDER, 
    COUNT(DISTINCT O.USER_ID) USERS
FROM ONLINE_SALE O INNER JOIN USER_INFO U ON O.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER;
