WITH A AS(
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
)

SELECT A.CATEGORY, A.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F INNER JOIN A 
ON F.CATEGORY = A.CATEGORY AND F.PRICE = A.MAX_PRICE
ORDER BY A.MAX_PRICE DESC;
