WITH A AS(
    SELECT *, DATEDIFF(END_DATE, START_DATE)+1 RENTAL_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR C USING (CAR_ID)
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P USING (CAR_TYPE)
    WHERE CAR_TYPE = '트럭'
)

SELECT
    HISTORY_ID,
    (CASE WHEN RENTAL_DURATION BETWEEN 7 AND 27
    THEN ROUND(DAILY_FEE*RENTAL_DURATION*0.95)
    WHEN RENTAL_DURATION BETWEEN 30 AND 89
    THEN ROUND(DAILY_FEE*RENTAL_DURATION*0.92)
    WHEN RENTAL_DURATION >= 90
    THEN ROUND(DAILY_FEE*RENTAL_DURATION*0.85)
    ELSE DAILY_FEE*RENTAL_DURATION END) FEE
FROM A
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;
