WITH COUNTER AS(
    SELECT H.HACKER_ID, H.NAME, COUNT(*) CNT
    FROM CHALLENGES C INNER JOIN HACKERS H ON C.HACKER_ID = H.HACKER_ID
    GROUP BY H.HACKER_ID, H.NAME
)

SELECT HACKER_ID, NAME, CNT CHALLENGES_CREATED
FROM COUNTER 
WHERE CNT IN (SELECT MAX(CNT) FROM COUNTER)
    OR CNT IN (SELECT CNT FROM COUNTER GROUP BY CNT HAVING COUNT(*) = 1)
ORDER BY CNT DESC, HACKER_ID;
