SELECT H.HACKER_ID, H.NAME, SUM(SQ.M_SCORE)
FROM (
    SELECT HACKER_ID, MAX(SCORE) M_SCORE
    FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID
) SQ LEFT JOIN HACKERS H ON SQ.HACKER_ID = H.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING SUM(SQ.M_SCORE) != 0
ORDER BY SUM(SQ.M_SCORE) DESC, H.HACKER_ID;
