SELECT
    MAX(CASE WHEN OCCUPATION = 'Doctor' THEN NAME END) 'Doctor',
    MAX(CASE WHEN OCCUPATION = 'Professor' THEN NAME END) 'Professor',
    MAX(CASE WHEN OCCUPATION = 'Singer' THEN NAME END) 'Singer',
    MAX(CASE WHEN OCCUPATION = 'Actor' THEN NAME END) 'Actor'
FROM 
    (SELECT *, RANK() OVER 
        (PARTITION BY OCCUPATION ORDER BY NAME) RN
     FROM OCCUPATIONS) A
GROUP BY RN;
