SELECT W.ID, P.AGE, W.COINS_NEEDED, W.POWER
FROM WANDS W INNER JOIN WANDS_PROPERTY P ON W.CODE = P.CODE
WHERE W.COINS_NEEDED IN (SELECT MIN(W1.COINS_NEEDED) MIN_COINS
                         FROM WANDS W1 INNER JOIN WANDS_PROPERTY P1 ON W1.CODE = P1.CODE
                         WHERE P1.IS_EVIL = 0 AND W.POWER = W1.POWER AND P.AGE = P1.AGE
                         GROUP BY P1.AGE, W1.POWER)
ORDER BY W.POWER DESC, P.AGE DESC;
