WITH RECURSIVE CTE AS(
    SELECT 0 N
    UNION ALL
    SELECT N+1
    FROM CTE
    WHERE N < 23
)

SELECT CTE.N HOUR, COUNT(A.ANIMAL_ID) COUNT
FROM ANIMAL_OUTS A 
RIGHT OUTER JOIN CTE ON HOUR(A.DATETIME) = CTE.N
GROUP BY CTE.N
ORDER BY HOUR;
